---
label: Default
hide_body: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    required: true
    options:
    - post
  label: Layout
  default: post
- type: text
  name: title
  label: Title
  config:
    required: true
- type: list
  name: tags
  label: tags
  default: []
