---
label: Default
hide_body: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    required: true
    options:
    - post
  label: Layout
  default: post
- type: text
  name: title
  label: Title
  config:
    required: true
- type: tag_list
  name: tags
  label: Tags
- type: datetime
  name: date
  label: Date
pages:
- _posts/2019-04-02-my-current-take-on-the-nsstatusbar-icon-size.md
